export const dummyItems = [
  {
    id: 1,
    type: "lost", // 'lost' or 'found'
    title: "Black Wallet",
    description: "Lost my black leather wallet containing my student ID and some cash.",
    category: "Wallets",
    location: "Main Library, 2nd Floor",
    date: "2026-03-18",
    contactEmail: "student1@college.edu",
    contactPhone: "555-0101",
    claimed: false,
    image: "https://images.unsplash.com/photo-1627123424574-724758594e9f?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: 2,
    type: "found",
    title: "Silver Macbook Air",
    description: "Found a Silver Macbook Air left on a bench outside the engineering building.",
    category: "Electronics",
    location: "Engineering Building North Entrance",
    date: "2026-03-19",
    contactEmail: "student2@college.edu",
    contactPhone: "555-0102",
    claimed: false,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: 3,
    type: "lost",
    title: "Hydroflask Water Bottle",
    description: "Blue Hydroflask with several stickers on it. Left in Room 104.",
    category: "Accessories",
    location: "Science Block, Room 104",
    date: "2026-03-15",
    contactEmail: "student3@college.edu",
    contactPhone: "555-0103",
    claimed: false,
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: 4,
    type: "found",
    title: "Keys with Lanyard",
    description: "A set of 3 keys on a red campus lanyard.",
    category: "Keys",
    location: "Cafeteria",
    date: "2026-03-17",
    contactEmail: "student4@college.edu",
    contactPhone: "555-0104",
    claimed: true,
    image: "https://images.unsplash.com/photo-1584650589803-519b9dabc555?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: 5,
    type: "lost",
    title: "Calculus Textbook",
    description: "James Stewart Calculus 8th Edition. My name is written on the inner cover.",
    category: "Books",
    location: "Student Union",
    date: "2026-03-16",
    contactEmail: "student5@college.edu",
    contactPhone: "555-0105",
    claimed: false,
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=400",
  },
];
